### ISSUE TITLE
window 编译败

### ISSUE THREAD

**Issue by zhenhuamo** [NanKeRen2020/linemode_template_match#1]
出现很多错误：如以下
linemodeTemplateMatch\utils.h:75: error: C2062: 意外的类型“bool”
linemodeTemplateMatch\utils.h:78: error: C2062: 意外的类型“float”
inemodeTemplateMatch\utils.cpp:134: error: C3861: “grid_max_reblur”: 找不到标识符
linemodeTemplateMatch\utils.cpp:250: error: C2065: “templ”: 未声明的标识符
linemodeTemplateMatch\utils.cpp:365: error: C2065: “show_image”: 未声明的标识符
linemodeTemplateMatch\utils.cpp:106: error: C2059: 语法错误:“delete”

**Comment by NanKeRen2020** [comment]
> 出现很多错误：如以下 linemodeTemplateMatch\utils.h:75: error: C2062: 意外的类型“bool” linemodeTemplateMatch\utils.h:78: error: C2062: 意外的类型“float” inemodeTemplateMatch\utils.cpp:134: error: C3861: “grid_max_reblur”: 找不到标识符 linemodeTemplateMatch\utils.cpp:250: error: C2065: “templ”: 未声明的标识符 linemodeTemplateMatch\utils.cpp:365: error: C2065: “show_image”: 未声明的标识符 linemodeTemplateMatch\utils.cpp:106: error: C2059: 语法错误:“delete”

编译环境是ubuntu1604, windows不保证能成功编译

**Comment by NanKeRen2020** [comment]
windows是可以编译成功的，不过不打算上传windows版
